stages:
  - deploy

deploy:
  stage: deploy
  image: $AND_DOCKER_PROXY_REGISTRY_NAME/alpine:3.17.3
  tags:
   - docker
  before_script: 
    - apk update
    - apk add --no-cache git rsync openssh-client
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - rsync -hrvz --exclude=.git ./ $SSHUSER@$SERVER:$APP_PATH
    - echo $ENV
    - ssh $SSHUSER@$SERVER "cd $APP_PATH && source $VENV && export $(echo $ENV | xargs) && sudo alembic upgrade head && sudo systemctl restart $SERVICE_NAME"
    #- ssh $SSHUSER@$SERVER "if [ "`curl --insecure -s https://127.0.0.1/-/health | jq .status`" != "up" ]; then echo "Success"; else "Error"; fi"
  only:
    - main 
