stages:
  - deploy

deploy:
  stage: deploy
  image: ubuntu:22
  tags:
   - docker
  before_script: 
    - apt-get update -y
    - apt-get install -y git rsync openssh-client
    - eval "$(ssh-agent -s)"
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    #- echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - rsync -hrvz --exclude=.git ./ $SSHUSER@$SERVER:$APP_PATH
    - ssh $SSHUSER@$SERVER "echo '$ENV' > $APP_PATH/.env"
    - ssh $SSHUSER@$SERVER "sudo systemctl restart $SERVICE_NAME"
    - ssh $SSHUSER@$SERVER "if [ "`curl --insecure -s https://127.0.0.1/-/health | jq .status`" != "up" ]; then echo "Success"; else "Error"; fi"
  only:
    - main 
