default_language_version:
    python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--settings-path", "pyproject.toml"]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ["--config", "pyproject.toml"]

  - repo: local
    hooks:
      - id: pylint
        args:
          - --disable=W0511
        name: pylint
        entry: pylint
        language: system
        types: [ python ]