version: '3.9'

services:
  postgres:
    image: postgres:14.6
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: helperapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  postgres_test:
    image: postgres:14.6
    ports:
      - 65432:5432
    environment:
      POSTGRES_DB: helperapp_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres_test:/var/lib/postgresql/data