FROM python:3.11

RUN mkdir /leadhelper_app

WORKDIR /leadhelper_app

COPY ./requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

CMD alembic upgrade head && uvicorn main:app --host=0.0.0.0 --port 80 --reload
