# Generated by Django 5.0.3 on 2024-03-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(max_length=50)),
                ('linkedin_profile', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('CONTACT', 'Contact'), ('DNM', 'Dnm'), ('REQUEST', 'Request'), ('DECLINED', 'Declined')], default='CONTACT', max_length=50)),
                ('next_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
