"""init

Revision ID: 202e9cc87cba
Revises: 
Create Date: 2024-01-22 19:25:11.502842

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "202e9cc87cba"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lead_contact",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lead_name", sa.String(), nullable=False),
        sa.Column("linkedin_profile", sa.String(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM("CONTACT", "DNM", "REQUEST", "DECLINED", name="typeenum"),
            nullable=True,
        ),
        sa.Column("next_contact", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_lead_contact_linkedin_profile"),
        "lead_contact",
        ["linkedin_profile"],
        unique=True,
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    op.drop_index(op.f("ix_lead_contact_linkedin_profile"), table_name="lead_contact")
    op.drop_table("lead_contact")
    # ### end Alembic commands ###
