"""add field

Revision ID: 3544e5e9bc93
Revises: a5267b38877e
Create Date: 2024-01-20 14:45:54.646870

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3544e5e9bc93'
down_revision: Union[str, None] = 'a5267b38877e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'token')
    # ### end Alembic commands ###
