"""Add initial data

Revision ID: 89076f590e4b
Revises: 
Create Date: 2024-01-04 19:43:37.337908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89076f590e4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_name', sa.String(), nullable=False),
    sa.Column('lead_company', sa.String(), nullable=True),
    sa.Column('linkedin_profile', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('CONTACT', 'DNM', name='typeenum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_linkedin_profile'), 'users', ['linkedin_profile'], unique=True)


    op.execute(
        """
        INSERT INTO admins (username, password) 
        VALUES ('AndersenLeads', 'eVxuw88jWpajhyJI'); 
        """
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_linkedin_profile'), table_name='users')
    op.drop_table('users')
    op.drop_table('admins')
    # ### end Alembic commands ###
